matrix:
  include:
  - language: generic
    services:
    - docker
    script:
    - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
    - docker-compose build
    - docker-compose push
    env:
    - secure: lBsJaI6EUq+lk6ByttG71RAOgzXpT3GvXpeD05OEDJwOFJw+BjlgmLA/Jeh6lRv7BZOJR5NGGk/tjsdMeN86M8+SLVkp7n5nW8Nhir66T2JvEWMQ3yfvGWv+UWaNVM0Oe/nsf9K2mMXlUKGmNPty1D+2q7D1kw3QXIQo6+IMSVo0e0jJgN1sBbgKFswohfbosBmlATBGayxYHxGYg+JFao3duPC183kt2Ar2iMTdkzKCITK07AbLH/gCBgxKnNHhz5ivpPzetQc9+IzdZY3Pi8dWMo/4PeKKap8mW6JHBgIR4BwwfI8iVnuZ63oKrw9OueXA1ikVNOZW3S2WOsIBf2AQJpf4MPHpceYhCohgkTFfiao9i4xhrkmGpCrbgKgjKUvKQUn8Gl50bcYaj228owZpQ3xDChb4w08SzS92BfgsdbxGQLE66ZbZ6lualfd1IwrtKdFq5Jv/L1njubiJXXdCdxzBA+nthI7NjfT2d5H2t3PVeiq5q3A9u1UE/LArPDlzLGTqj6bcT3Cp3X8hEiC+nOciSvtrjhrM2a6Mr3XNfQHBDqZ1HDcCzT3JGnjMLGISkUo8u7/dVf3oAQaAHYay4LmV/rFI83yR+6/BVuH9FvdjC7UTyyc62bpNYC57DWxhOhME2MegrN+FHM46CZAiqJMQYJdNdC5MtCJ/CfQ=
    - DOCKER_USERNAME: johnazoidberg
  - language: android
    android:
      components:
      - build-tools-28.0.3
      - android-28
    install:
    - yes | sdkmanager --list
    script:
    - cd frontend-app/AIAssistent/
    - "./gradlew build"
    deploy:
    - provider: releases
      api_key: "$GITHUB_OAUTH_TOKEN"
      file: app/build/outputs/apk/debug/app-debug.apk
      skip_cleanup: true
      draft: true
      on:
        branch:
        - publish-android
        - travis-test
env:
  global:
    secure: M8r9Y/qfXGG/kWPYx3zi/d5jGXFI0LiX8077pa8hTa8+YxJ9VcihQdvJkjw5xCVzVxJl106cyRqCAc2D2ANTAVYc7Z1/mK5aCK5HOCzvgN7ZtXWU8kyRlwNpLqEcEhzmMZ6B9DZnuYBiAUczxaePze5zT464ZApe/eObRhaZzp4iZuA5udwKZdxlqluh57+WEmeMo40QF8WBw4XrmaVePaFlTmAKd1wYoLk40K/c7fVXtOKbaKTK2qFGTrnkruvYNgaaFjIJ8OYk+2PU3qkCJSVZhLQpcwFcuFP2ExNjLeXSwF7Mmw0y068CJ6hBt8AbUoonaJ0qzjtb1BV/tzz2fafrPjHPLzGlqWn8DBSEN6RGEi6ZAA0qLJrJpR+FGtL8r2FdAhNseKhHRnuZ3UGVLrgMePf/2nl5Z1eDuq3EUw3qRld1uyyO6RxRYkG3R9Y8aIOGJYkYi/P3GceZ3/h0LaNo2YyEobRTJWPlgZwHxk6gDZnA9kFVoO9eKbKcEcgjq96Lvt+TaU7HeqPbzSKXg4ttKYyOISqEe94t2tjAFfl0qwnGX8V+bhrR5LQm9C40WQ0re39aL/Czs3lc8lWfQk0o7rgJtWASXUFJEhzl6+KtTPx2X10Ps3TKOyXufJs+he912dXrk3zwG9ccK1bi4j/WjvwpgpgG0DmTVH2CrE4=
before_install:
- openssl aes-256-cbc -K $encrypted_0792f20bc84d_key -iv $encrypted_0792f20bc84d_iv
  -in Configuration.java.enc -out frontend-app/AIAssistent/app/src/main/java/com/example/aiassistent/Configuration.java
  -d
