version: '3'
services:
  database:
    image: redis:5
    volumes:
      - db-data:/data
#     - ./infrastructure/redis.conf:/usr/local/etc/redis/redis.conf
    expose:
      - 6379
  reverse-proxy:
    image: abiosoft/caddy:latest
    volumes:
      - ./infrastructure/Caddyfile:/etc/Caddyfile
    ports:
      - 80:80
      - 443:443
      - 2015:2015
  trigger-router:
    build: ./trigger-router
    image: johnazoidberg/sm-trigger-router
    expose:
      - 5000
  feinstaub-adapter:
    build: ./feinstaub-adapter
    image: johnazoidberg/sm-feinstaub-adapter
    expose:
      - 5001
  calendar-adapter:
     build: ./calendar-adapter
     image: johnazoidberg/sm-calendar-adapter
     expose:
       - 5002
  pollen-adapter:
    build: ./pollen-adapter
    image: johnazoidberg/sm-pollen-adapter
    expose:
      - 5003
  wetter-adapter:
    build: ./wetter-adapter
    image: johnazoidberg/sm-wetter-adapter
    expose:
      - 5004
  verkehr-adapter:
    build: ./verkehr-adapter
    image: johnazoidberg/sm-verkehr-adapter
    expose:
      - 5005
  vvs-adapter:
    build: ./vvs-adapter
    image: johnazoidberg/sm-vvs-adapter
    expose:
      - 5006
  goodmorning-usecase:
    build: ./goodmorning-usecase
    image: johnazoidberg/sm-goodmorning-usecase
    expose:
      - 5010
  personaltrainer-usecase:
    build: ./personaltrainer-usecase
    image: johnazoidberg/sm-personaltrainer-usecase
    expose:
      - 5011
  setup-usecase:
    build: ./setup-usecase
    image: johnazoidberg/sm-setup-usecase
    expose:
     - 5012
  daily-overview-usecase:
    build: ./daily-overview-usecase
    image: johnazoidberg/sm-daily-overview-usecase
    expose:
     - 5013
  homeoffice-usecase:
    build: ./homeoffice-usecase
    image: johnazoidberg/sm-homeoffice-usecase
    expose:
     - 5014
volumes:
  db-data:
    driver: local
