version: '3'
services:
  reverse-proxy: 
    image: abiosoft/caddy:latest
    volumes:
      - ./infrastructure/Caddyfile:/etc/Caddyfile
    ports:
      - 80:80
      - 443:443
      - 2015:2015
    links:
      - trigger-router
      - feinstaub-adapter
  trigger-router:
    build: ./trigger-router
    image: johnazoidberg/sm-trigger-router
    expose:
      - 5000
  feinstaub-adapter:
    build: ./feinstaub-adapter
    image: johnazoidberg/sm-feinstaub-adapter
    expose:
      - 5001
  calendar-adapter:
   build: ./calendar-adapter
   image: johnazoidberg/sm-calendar-adapter
   expose:
     - 5002
